services:
  - type: web
    name: uem-lab-inventory
    runtime: node
    plan: free
    buildCommand: npm install --include=dev && npx prisma generate && npm run build
    preDeployCommand: npx prisma migrate deploy
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
